server:
  httpListenAddr: ':3592'
  adminAPI:
    enabled: true

storage:
  driver: disk
  disk:
    directory: ./cerbos-service/policies
    watchForChanges: true

audit:
  enabled: true
  accessLogsEnabled: true
  decisionLogsEnabled: true
  backend: file
  file:
    path: ./cerbos-service/logs
