name: Infra (CDK)

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment (e.g., dev, stg, prod)'
        required: true
        default: 'dev'
      app_name:
        description: 'Stack app name (e.g., core-apis)'
        required: true
        default: 'core-apis'
      region:
        description: 'AWS region'
        required: true
        default: 'eu-west-1'
      create_oidc:
        description: 'Also create GitHub OIDC role stack? (true/false)'
        required: false
        default: 'false'

jobs:
  cdk:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ENV: ${{ inputs.env }}
      APP_NAME: ${{ inputs.app_name }}
      AWS_REGION: ${{ inputs.region }}
      CREATE_OIDC: ${{ inputs.create_oidc }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK deps
        run: npm ci

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Bootstrap (first time per account/region)
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
          npx cdk bootstrap aws://$ACCOUNT_ID/${AWS_REGION}

      - name: Deploy Network
        run: |
          npx cdk deploy --require-approval never \
            "${ENV}-${APP_NAME}-network" \
            -c env=${ENV} -c appName=${APP_NAME} -c region=${AWS_REGION}

      - name: Deploy ECR
        run: |
          npx cdk deploy --require-approval never \
            "${ENV}-${APP_NAME}-ecr" \
            -c env=${ENV} -c appName=${APP_NAME} -c region=${AWS_REGION}

      - name: Deploy Service (initial, imageTag=latest)
        run: |
          npx cdk deploy --require-approval never \
            "${ENV}-${APP_NAME}-svc" \
            -c env=${ENV} -c appName=${APP_NAME} -c region=${AWS_REGION} \
            -c imageTag=latest

      - name: (Optional) Create OIDC role stack
        if: ${{ env.CREATE_OIDC == 'true' }}
        run: |
          npx cdk deploy --require-approval never \
            "${ENV}-${APP_NAME}-gh-oidc" \
            -c env=${ENV} -c appName=${APP_NAME} -c region=${AWS_REGION} \
            -c createOidc=true \
            -c githubOrg=${{ github.repository_owner }} \
            -c githubRepo=${{ github.event.repository.name }}
